version: '3.1'
services:
  tesla-ble-http-proxy:
    image: wimaha/tesla-ble-http-proxy:latest
    container_name: tesla-ble-http-proxy
    ports:
      - "8080:8080"
    volumes:
      - ~/TeslaBleHttpProxy/key:/key
      - /var/run/dbus:/var/run/dbus
    restart: always
    environment: #optional
      logLevel: debug
      httpListenAddress: :8080
